apiVersion: bootstrap.cluster.x-k8s.io/v1alpha4
kind: KubeadmConfigTemplate
metadata:
    name: cluster-a-md-1
    namespace: default
spec:
    template:
        spec:
            files:
                - content: |-
                    #!/bin/bash
                    for i in $(ls /run/kubeadm/ | grep 'kubeadm.yaml\|kubeadm-join-config.yaml'); do
                      cat <<EOF>> "/run/kubeadm//$i"
                    ---
                    kind: KubeProxyConfiguration
                    apiVersion: kubeproxy.config.k8s.io/v1alpha1
                    metricsBindAddress: "0.0.0.0:10249"
                    EOF
                    done
                  path: /run/kubeadm/konvoy-set-kube-proxy-configuration.sh
                  permissions: "0700"
                - content: |-
                    [metrics]
                      address = "0.0.0.0:1338"
                      grpc_histogram = false
                  path: /etc/containerd/conf.d/konvoy-metrics.toml
                  permissions: "0644"
            joinConfiguration:
                nodeRegistration:
                    criSocket: /run/containerd/containerd.sock
                    kubeletExtraArgs:
                        cloud-provider: ""
                        volume-plugin-dir: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/
            preKubeadmCommands:
                - systemctl daemon-reload
                - systemctl restart containerd
                - /run/kubeadm/konvoy-set-kube-proxy-configuration.sh
