apiVersion: infrastructure.cluster.konvoy.d2iq.io/v1alpha1
kind: PreprovisionedMachineTemplate
metadata:
    name: cluster-a-md-1
    namespace: default
spec:
    template:
        spec:
            inventoryRef:
                name: cluster-a-md-1
                namespace: default
            overrideRef:
                name: cluster-a-md-1-gpuRegOverride
                namespace: default
