apiVersion: cluster.x-k8s.io/v1alpha4
kind: MachineDeployment
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: cluster-a
  name: cluster-a-md-0
  namespace: default
spec:
  clusterName: cluster-a
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 8
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: cluster-a
      cluster.x-k8s.io/deployment-name: cluster-a-md-0
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: cluster-a
        cluster.x-k8s.io/deployment-name: cluster-a-md-0
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha4
          kind: KubeadmConfigTemplate
          name: cluster-a-md-0
      clusterName: cluster-a
      infrastructureRef:
        apiVersion: infrastructure.cluster.konvoy.d2iq.io/v1alpha1
        kind: PreprovisionedMachineTemplate
        name: cluster-a-md-0
      version: v1.21.6
---
apiVersion: infrastructure.cluster.konvoy.d2iq.io/v1alpha1
kind: PreprovisionedMachineTemplate
metadata:
  name: cluster-a-md-0
  namespace: default
spec:
  template:
    spec:
      inventoryRef:
        name: cluster-a-md-0
        namespace: default
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha4
kind: KubeadmConfigTemplate
metadata:
  name: cluster-a-md-0
  namespace: default
spec:
  template:
    spec:
      files:
        - content: |-
            #!/bin/bash
            # CAPI does not expose an API to modify KubeProxyConfiguration
            # this is a workaround to use a script with preKubeadmCommand to modify the kubeadm config files
            # https://github.com/kubernetes-sigs/cluster-api/issues/4512
            for i in $(ls /run/kubeadm/ | grep 'kubeadm.yaml\|kubeadm-join-config.yaml'); do
              cat <<EOF>> "/run/kubeadm//$i"
            ---
            kind: KubeProxyConfiguration
            apiVersion: kubeproxy.config.k8s.io/v1alpha1
            metricsBindAddress: "0.0.0.0:10249"
            EOF
            done
          path: /run/kubeadm/konvoy-set-kube-proxy-configuration.sh
          permissions: "0700"
        - content: |2
            [metrics]
              address = "0.0.0.0:1338"
              grpc_histogram = false
          path: /etc/containerd/conf.d/konvoy-metrics.toml
          permissions: "0644"
      joinConfiguration:
        nodeRegistration:
          criSocket: /run/containerd/containerd.sock
          kubeletExtraArgs:
            cloud-provider: ""
            volume-plugin-dir: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/
      preKubeadmCommands:
        - systemctl daemon-reload
        - systemctl restart containerd
        - /run/kubeadm/konvoy-set-kube-proxy-configuration.sh
